### ISSUE TITLE
miss the SysInfoX64.dll file

### ISSUE THREAD

**Issue by witkey** [KunYi/DumpACPI#1]
Hi sir, 

1. Complie with Win32, and run the DumpACPI.exe as Administrator in CMD, but can't get any thing.
2. Complie with x64, and run the DumpACPI.exe as Administrator in CMD,  will report "Can't find SysInfo.dll", i want that the SysInfo.dll file is not x64, so could you upload the SysInfoX64.dll? 

Thank you.

**Comment by KunYi** [comment]
> Hi sir,
> 
>     1. Complie with Win32, and run the DumpACPI.exe as Administrator in CMD, but can't get any thing.

the Win32 mode should be work with Administrator, have been verification some difference computer 
 
maybe try to launch Visual Studio with Administrator (ref. https://www.digitalcitizen.life/how-run-programs-administrator-windows-7), then use Debug mode to observe the code flow

another suggestion test with VirtualBox VM, due to the code find RSDP from E/F Segment
see "5.2.5.1 Finding the RSDP on IA-PC Systems" (https://www.uefi.org/sites/default/files/resources/ACPI_6_2.pdf)

> 
>     2. Complie with x64, and run the DumpACPI.exe as Administrator in CMD,  will report "Can't find SysInfo.dll", i want that the SysInfo.dll file is not x64, so could you upload the SysInfoX64.dll?

Yes, the code missed about x64 support, I will fix the issues
Thank you report the issues
> 
> 
> Thank you.

**Comment by KunYi** [comment]
@witkey , please try latest commit "[8d2a64a91998c94a7c8494f13aff27e4b9182a57](https://github.com/KunYi/DumpACPI/commit/8d2a64a91998c94a7c8494f13aff27e4b9182a57)"
the commit will support x64 build
and add a screenshot for demo debug with visual studio

![Debug Screenshot](https://raw.githubusercontent.com/KunYi/DumpACPI/8d2a64a91998c94a7c8494f13aff27e4b9182a57/Docs/DumpACPI.PNG)
